#!/bin/bash
#
# SPDX-License-Identifier: GPL-2.0-or-later
#
# SPDX-FileCopyrightText: 2016-2025 KUNBUS GmbH

. /etc/os-release

# reset environment
if [ "$(/usr/bin/env | /bin/grep -Ev '^(PWD|SHLVL|_)=')" ]; then
	exec /usr/bin/env - /bin/bash "$0" "$@"
fi

CONFIG=/boot/firmware/config.txt
CMDLINE=""

trap "exit 1" SIGUSR1
PROC="$$"

if [ "$VERSION_ID" -ge 12 ]; then
    CMDLINE="/boot/firmware/cmdline.txt"
else
    CMDLINE="/boot/cmdline.txt"
fi

usage() {
	cat <<-EOF
		Usage: $(basename "$0") enable | disable | status | available | set | get <feature>
		Supported features: gui revpi-con-can
		                    var-log.mount dphys-swapfile
		                    teamviewer-revpi pimodbus-master
		                    pimodbus-slave systemd-timesyncd ssh
		                    logi-rts nodered noderedrevpinodes-server
		                    revpipyload bluetooth ieee80211 avahi
		                    external-antenna wifi_country
	EOF
}

# do_gui <verb>
do_gui() {
	case "$1" in
	enable)
		/bin/systemctl set-default graphical.target
		;;
	disable)
		/bin/systemctl set-default multi-user.target
		;;
	status)
		[ "$(/bin/systemctl get-default)" != "graphical.target" ]
		return
		;;
	availstat)
		if do_gui available; then
			return 2
		fi
		do_gui status "$2"
		return
		;;
	available)
		if [ -e /usr/bin/startx ]; then
			return 1
		else
			return 0
		fi
		;;
	esac
}

rpi_revision_code() {
	# see https://www.raspberrypi.com/documentation/computers/raspberry-pi.html#new-style-revision-codes
	code=$(grep Revision /proc/cpuinfo | cut -d' ' -f2)

	if [ -z "$code" ]; then
		echo >&2 "Unable to determine board revision code. Not running on a RevPi?. Aborting."
		# we are running in a subshell, thus cannot exit directly here
		kill -10 "$PROC"
		return
	fi

	# Convert the hexadecimal revision code to base 10
	echo $((16#${code}))
}

rpi_type() {
	code=$(rpi_revision_code)
	mask=4080

	echo $(((code & mask) >> 4))
}

is_cm1() {
	test "$(rpi_type)" -eq 6
}

is_not_cm1() {
	! is_cm1
}

is_cm3() {
	test "$(rpi_type)" -eq 10
}

is_cm4s() {
	test "$(rpi_type)" -eq 21
}

is_cm4() {
	test "$(rpi_type)" -eq 20
}

is_cm5() {
	test "$(rpi_type)" -eq 24
}

is_cm_with_wifi() {
	if is_cm4 || is_cm5 && grep -q 'DRIVER=brcmfmac' /sys/class/ieee80211/phy0/device/uevent 2>/dev/null; then
		return 0
	else
		return 1
	fi
}

is_revpi_connect() {
	is_cm3 || is_cm4s && /bin/grep -F -q 'kunbus,revpi-connect' /proc/device-tree/compatible
}

get_config_var() {
	/bin/grep -E "^[[:blank:]]*${1}=" "$CONFIG" |
		/usr/bin/cut -d= -f2- | /usr/bin/tail -1
}

clear_config_var() {
	/bin/sed -r -i -e "/^[[:blank:]]*${1}=${2}/d" "$CONFIG"
	/bin/sync
}

set_config_var() {
	if [ "$(get_config_var $1)" = "$2" ]; then
		return
	fi
	clear_config_var "$1"
	echo "$1=$2" >>"$CONFIG"
	/bin/sync
}

# do_config <verb> <variable-name> <variable-value> <available-hook>
do_config() {
	case "$1" in
	enable)
		set_config_var "$2" "$3"
		;;
	disable)
		clear_config_var "$2" "$3"
		;;
	status)
		val="$(get_config_var $2)"
		if [ -z "$val" ]; then
			echo -n "0 "
		else
			echo -n "$val "
		fi
		if [ -n "$3" ]; then
			[ "$3" != "$val" ]
			return
		else
			[ -z "$val" ]
			return
		fi
		;;
	available)
		eval "$4"
		[ $? = 1 ]
		return
		;;
	availstat)
		if do_config available "$2" "$3" "$4"; then
			return 2
		fi
		do_config status "$2" "$3" "$4"
		return
		;;
	esac
}

# do_overlay <verb> <overlay-name> <available-hook>
do_overlay() {
	case "$1" in
	enable)
		clear_config_var "dtoverlay" "$2"
		echo "dtoverlay=$2" >>"$CONFIG"
		/usr/bin/dtoverlay "$2"
		;;
	disable)
		clear_config_var "dtoverlay" "$2"
		/usr/bin/dtoverlay -r "$2"
		;;
	status)
		/bin/grep -E -q "^[[:blank:]]*dtoverlay=$2" "$CONFIG"
		[ $? = 1 ]
		return
		;;
	available)
		eval "$3"
		[ $? = 1 ]
		return
		;;
	availstat)
		if do_overlay available "$2" "$3"; then
			return 2
		fi
		do_overlay status "$2" "$3"
		return
		;;
	esac
}

avahi-daemon-post-disable() {
	# Disable the avahi socket AFTER disabling the service unit
	# Note: This is because a connected socket could interrupt stop
	/bin/systemctl disable avahi-daemon.socket
	/bin/systemctl stop avahi-daemon.socket
}
avahi-daemon-post-enable() {
	# Enable the avahi socket after enabling the service unit
	/bin/systemctl enable avahi-daemon.socket
	/bin/systemctl start avahi-daemon.socket
}

dphys-swapfile-post-disable() {
	# remove swapfile
	/sbin/dphys-swapfile uninstall
}

var-log.mount-pre-enable() {
	# disable is no longer sufficient on stretch
	/bin/systemctl unmask var-log.mount
}

var-log.mount-post-disable() {
	/bin/systemctl mask var-log.mount
}

# do_service <verb> <service>
do_service() {
	declare -f "$2-pre-$1" >/dev/null 2>&1 && eval "$2-pre-$1"
	case "$1" in
	enable)
		/bin/systemctl enable "$2"
		/bin/systemctl start "$2"
		;;
	disable)
		/bin/systemctl disable "$2"
		/bin/systemctl stop "$2"
		;;
	status)
		/bin/systemctl is-enabled "$2" >/dev/null 2>&1
		[ $? = 1 ]
		return
		;;
	available)
		/bin/systemctl status "$2" 2>&1 | /bin/grep -qE "not(-| be )found"
		return
		;;
	availstat)
		if do_service available "$2"; then
			return 2
		fi
		do_service status "$2"
		return
		;;
	esac
	ret=$?
	declare -f "$2-post-$1" >/dev/null 2>&1 && eval "$2-post-$1"
	return $ret
}

# do_wireless <verb> <type> (where type is "bluetooth" or "ieee80211")
do_wireless() {
	shopt -s nullglob
	if is_cm_with_wifi || grep -q "revpi-flat" "/proc/device-tree/compatible"; then
		if [ "$2" = "ieee80211" ]; then
			#built-in devices are recognizable by having a devicetree node
			IDX=(/sys/class/"$2"/*)
			if grep -q -E 'DRIVER=(brcmfmac|mwifiex_sdio)' "$IDX"/device/uevent; then
				# search for rfkill directory
				IDX=("$IDX"/rfkill*)
				# strip everything except index
				IDX="${IDX##*/rfkill}"
			fi
		else
			hci_device="/sys/class/bluetooth/hci0"

			if [ ! -L $hci_device ]; then
				# The bluetooth device is not present and
				# the device should have been brought up by revpi-bluetooth's udev rules
				# or vendor magic (devices based on CM4 and newer). Nothing we can do here,
				# so treat the interface as disabled.
				return 0
			fi

			IDX=$(cat "$hci_device"/rfkill*/index)
		fi
	fi
	shopt -u nullglob

	case "$1" in
	enable)
		[ "$IDX" ] && rfkill unblock "$IDX"
		;;
	disable)
		[ "$IDX" ] && rfkill block "$IDX"
		;;
	status)
		[ -z "$IDX" ] && return 0
		disabled=$(</sys/class/rfkill/rfkill"$IDX"/soft)
		# invert value
		((disabled))
		return
		;;
	available)
		[ -z "$IDX" ]
		return
		;;
	availstat)
		[ -z "$IDX" ] && return 2
		disabled=$(</sys/class/rfkill/rfkill"$IDX"/soft)
		# invert value
		((disabled))
		return
		;;
	esac
}

do_cm_external_antenna() {
	case "$1" in
	enable)
		clear_config_var "dtparam" "ant1"
		clear_config_var "dtparam" "ant2"
		echo "dtparam=ant2" >>"$CONFIG"
		;;
	disable)
		clear_config_var "dtparam" "ant1"
		clear_config_var "dtparam" "ant2"
		;;
	status)
		/bin/grep -E -q "^[[:blank:]]*dtparam=ant2$" "$CONFIG"
		[ $? = 1 ]
		return
		;;
	available)
		is_cm_with_wifi
		[ $? = 1 ]
		return
		;;
	availstat)
		if do_cm_external_antenna available; then
			return 2
		fi
		do_cm_external_antenna status
		return
		;;
	esac
}

set_wifi_country() {
    local country="$1"
    
    if [ -z "$country" ]; then
        echo >&2 "No country code provided. Usage: set wifi_country <COUNTRY_CODE>"
        return
    fi
    
	if ! grep -q "^${country}[[:space:]]" /usr/share/zoneinfo/iso3166.tab; then
        echo >&2 "Invalid country code: $country. Must be an ISO 3166-1 alpha-2 code."
        return
    fi

    echo "Setting WiFi country to $country"
    # This code for setting the WiFi country is partially taken from the Raspberry Pi's
    # raspi-config script, which is licensed under the MIT License.
    # Original code can be found here:
    # https://github.com/RPi-Distro/raspi-config/blob/bbea4d8d03eb3fb642d9738456635a026a2c842b/raspi-config#L891-L894
    # SPDX-SnippetBegin
    # SPDX-License-Identifier: MIT
    # SPDX-SnippetCopyrightText: 2012 Alex Bradbury <asb@asbradbury.org>
    sed -i \
        -e "s/\s*cfg80211.ieee80211_regdom=\S*//" \
        -e "s/\(.*\)/\1 cfg80211.ieee80211_regdom=$country/" \
        "$CMDLINE"
	# SPDX-SnippetEnd
    iw reg set "$country"
}

get_wifi_country() {
    local regdomain
    # This code for getting the WiFi country is partially taken from the Raspberry Pi's
    # raspi-config script, which is licensed under the MIT License.
    # Original code can be found here:
    # https://github.com/RPi-Distro/raspi-config/blob/bbea4d8d03eb3fb642d9738456635a026a2c842b/raspi-config#L857-L871
    # SPDX-SnippetBegin
    # SPDX-License-Identifier: MIT
    # SPDX-SnippetCopyrightText: 2012 Alex Bradbury <asb@asbradbury.org>
    if grep -q "cfg80211.ieee80211_regdom=" "$CMDLINE"; then
        regdomain="$(sed -n 's/.*cfg80211.ieee80211_regdom=\(\S*\).*/\1/p' "$CMDLINE")"
    else
        regdomain="$(iw reg get | sed -n "0,/country/s/^country \(.\+\):.*$/\1/p")"
    fi
    if [ -z "$regdomain" ] \
        || ! grep -q "^${regdomain}[[:space:]]" /usr/share/zoneinfo/iso3166.tab; then
        return 1
    fi
    echo "$regdomain"
    return 0
    # SPDX-SnippetEnd
}

do_wifi_country() {
    local cmd="$1"
    local country="$2"

    case "$cmd" in
    "set")
        set_wifi_country "$country"
        ;;
    get)
        get_wifi_country
        ;;
    esac
}

if [ "$1" != enable ] &&
	[ "$1" != disable ] &&
	[ "$1" != status ] &&
	[ "$1" != available ] &&
	[ "$1" != availstat ] &&
	[ "$1" != "set" ] &&
	[ "$1" != "get" ]; then
	usage
	exit
fi

cmd="$1"
shift
while [ $# -gt 0 ]; do
	svc="$1"
	case "$svc" in
	gui)
		do_gui "$cmd"
		;;
	revpi-con-can)
		do_overlay "$cmd" "$svc" is_revpi_connect
		;;
	var-log.mount)
		do_service "$cmd" "$svc"
		;;
	dphys-swapfile)
		do_service "$cmd" "$svc"
		;;
	teamviewer-revpi)
		do_service "$cmd" "$svc"
		;;
	pimodbus-master)
		do_service "$cmd" "$svc"
		;;
	pimodbus-slave)
		do_service "$cmd" "$svc"
		;;
	systemd-timesyncd)
		do_service "$cmd" "$svc"
		;;
	ssh)
		do_service "$cmd" "$svc"
		;;
	logi-rts)
		do_service "$cmd" "$svc"
		;;
	nodered)
		do_service "$cmd" "$svc"
		;;
	noderedrevpinodes-server)
		do_service "$cmd" "$svc"
		;;
	revpipyload)
		do_service "$cmd" "$svc"
		;;
	avahi)
		do_service "$cmd" avahi-daemon
		;;
	bluetooth)
		do_wireless "$cmd" "$svc"
		;;
	ieee80211)
		do_wireless "$cmd" "$svc"
		;;
	external-antenna)
		do_cm_external_antenna "$cmd"
		;;
	wifi_country)
	    shift
		do_wifi_country "$cmd" "$1"
		;;
	*)
		usage
		exit
		;;
	esac
	echo -n "$? "
	shift
done

echo
