.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2019 Kunbus GmbH
.\"
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH pibridge-shutdown 8 "February 27 2019"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
pibridge-shutdown \- shut down a PiBridge Ethernet interface if no gateway is attached
.SH SYNOPSIS
.B pibridge-shutdown <interface>
.SH DESCRIPTION
On the RevPi Core, the interrupt pin of the two PiBridge Ethernet interfaces
is not connected.  The interrupt must therefore be polled, which occupies
about 10% of one CPU core of a Compute Module 3. That's a waste of resources
if no gateway is attached. \fBpibridge-shutdown\fP therefore checks the carrier
state upon system boot and shuts the interface down if no carrier is detected.
It also tells dhcpcd to no longer manage the interface.

The issue is not present on the RevPi Connect, so PiBridge interfaces need
not be shut down on this product. \fBpibridge-shutdown\fP identifies affected
products by checking whether a valid interrupt is defined in the DeviceTree.

.B pibridge-shutdown
is invoked by the systemd units pileft.service and piright.service, which in
turn are "wanted by" the systemd units pileft.device and piright.device via
appropriate udev rules in /lib/udev/rules.d/50-revpi.rules.
.SH SEE ALSO
For more information on Revolution Pi visit
.IR https://revolutionpi.kunbus.com
