.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2016-2017 Kunbus GmbH
.\"
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH revpi-sos 1 "July 27 2020"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
revpi-sos \- collect the information for RevPi related problems debugging
.SH SYNOPSIS
.B revpi-sos
.RI [ options ]
.SH DESCRIPTION
.B revpi-sos
base on sosreport(1) to collect the needed information for debugging.
.TP
The information includes following files:
.br
/var/log/messages
.br
/var/log/kern.log
.br
/var/log/daemon.log
.br
/var/log/apache2/error.log
.br
/var/www/pictory/projects/_config.rsc
.br
/boot/cmdline.txt
.br
/boot/config.txt
.br
/etc/dhcpcd.conf
.br
/etc/resolv.conf
.br
/etc/revpi/image-release
.br
/etc/network/interfaces
.TP
and output of following commands:
.br
df -h
.br
dmesg
.br
uname -a
.br
piTest -d
.br
ps -ax
.br
lsusb -v
.br
free
.br
apt-cache show pictory
.br
apt-cache show revpi-webstatus
.br
apt-cache show raspberrypi-kernel
.br
netstat -ln
.br
ls /dev/ttyUSB*
.br
ls /dev/ttyRS485
.br
ls -l /etc/revpi/config.rsc
.br
vcgencmd version
.br
vcgencmd measure_temp
.br
vcgencmd measure_clock arm
.SH OPTIONS
.TP
.B \-f
Execute without confirmation(generating the report and change the ownership to current user).
.TP
.B \-h
Show the help list.
.SH SEE ALSO
For more information on Revolution Pi visit
.IR https://revolutionpi.com
