#!/bin/bash
#
# SPDX-License-Identifier: GPL-2.0
#
# Copyright: 2021-2023 KUNBUS GmbH
#

set -e

# shellcheck source=set-mac-functions
source /usr/share/revpi/set-mac-functions

interface="$1"
mac="$2"

check_args_usage "$@"

check_mac "$mac"
set_mac_ks8851 "$interface" "$mac"
